/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.otpjava;

import java.util.Arrays;

/**
 *
 * @author Marko
 */
public class GUIOTP extends javax.swing.JFrame {

    /**
     * Creates new form GUIOTP
     */
    public GUIOTP() {
        initComponents();
        setTitle("OTP sifra za privatnu upotrebu");
    }
    OTPmetode otp = new OTPmetode();
    byte[] kljuc = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        duzinaKljucaInput = new javax.swing.JTextField();
        lozinkaInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        generisiKljucDugme = new javax.swing.JButton();
        sifrujDugme = new javax.swing.JButton();
        desifrujDugme = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        duzinaKljucaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duzinaKljucaInputActionPerformed(evt);
            }
        });

        lozinkaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lozinkaInputActionPerformed(evt);
            }
        });

        jLabel1.setText("Generisanje kljuca: ");

        jLabel2.setText("Duzina kljuca");

        jLabel3.setText("Lozinka");

        generisiKljucDugme.setText("Generisi kljuc");
        generisiKljucDugme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generisiKljucDugmeActionPerformed(evt);
            }
        });

        sifrujDugme.setText("Sifruj");
        sifrujDugme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifrujDugmeActionPerformed(evt);
            }
        });

        desifrujDugme.setText("Desifruj");
        desifrujDugme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desifrujDugmeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(duzinaKljucaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(16, 16, 16)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lozinkaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(37, 37, 37)))
                .addGap(28, 28, 28)
                .addComponent(generisiKljucDugme, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(desifrujDugme, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(sifrujDugme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(duzinaKljucaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lozinkaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generisiKljucDugme))
                .addGap(36, 36, 36)
                .addComponent(sifrujDugme, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(desifrujDugme, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //mora se izgenerisati kljuc iste duzine kao i fajl koji se sifruje!!!!!
    private void generisiKljucDugmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generisiKljucDugmeActionPerformed
        int duzina_kljuca = Integer.parseInt(this.duzinaKljucaInput.getText());
        String lozinka = this.lozinkaInput.getText();
        long lozinka_l = Long.parseLong(lozinka);
        if(lozinka.length() >= 8){                                                           //ne prihvatamo lozinku ispod 8 karaktera
            //this.kljuc = this.otp.generisiKljuc(duzina_kljuca, Long.parseLong(lozinka));    //ako zelimo da napravimo da korisnik moze da zadaje lozinku, i da unese koje god velicine, izracunacemo hash vrednost sa sh1 funkcijom, dobicemo 160 bitova i uzecemo onoliko koliko nam je potrebno za long (ako je otisak 160 bitova, nama je max vrednost 64 bita, prva 64 bita cemo izdvojiti i izvrsiti konverziju u long)
            
            this.otp.sacuvajFajl(this.otp.generisiKljuc(duzina_kljuca, lozinka_l), "Unesite naziv fajla u kom ce se cuvati kljuc");    //ovo sam dodao da mi zapravo napravi fajl sa tim kljucem
            System.out.println("kljuc: " + lozinka_l);
            System.out.println(Arrays.toString(this.kljuc));
        }else{
            this.otp.sacuvajFajl(this.otp.generisiKljuc(duzina_kljuca), "Unesite naziv fajla u kom se cuvati kljuc");
        }
    }//GEN-LAST:event_generisiKljucDugmeActionPerformed

    private void duzinaKljucaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duzinaKljucaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duzinaKljucaInputActionPerformed

    private void lozinkaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lozinkaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lozinkaInputActionPerformed

    private void sifrujDugmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifrujDugmeActionPerformed
        byte [] otvorenaPoruka = this.otp.ucitajFajl("Izaberite vec postojeci fajl u kom se nalazi poruka za sifrovanje");
        this.duzinaKljucaInput.setText(otvorenaPoruka.length + "");              // + "" nam sluzi da efikasnije pretvorimo u string int koji vraca .length
        byte [] kljuc = this.otp.ucitajFajl("Izaberite postojeci fajl u kom se nalazi kljuc.");
        this.otp.sacuvajFajl(this.otp.sifrujDesifruj(otvorenaPoruka, kljuc), "Unesite naziv novog fajla u kom ce se cuvati sifrat");
                
    }//GEN-LAST:event_sifrujDugmeActionPerformed

    private void desifrujDugmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desifrujDugmeActionPerformed
        byte [] sifrat = this.otp.ucitajFajl("Izaberite vec postojeci fajl u kom se nalazi sifrat koji zelite da desifrujete");
        this.duzinaKljucaInput.setText(sifrat.length + "");           
        byte [] kljuc = this.otp.ucitajFajl("Izaberite postojeci fajl u kom se nalazi kljuc");
        this.otp.sacuvajFajl(this.otp.sifrujDesifruj(sifrat, kljuc), "Unesite naziv novog fajla u kom ce se cuvati desifrovana otvorena poruka");
    }//GEN-LAST:event_desifrujDugmeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIOTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIOTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIOTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIOTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIOTP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton desifrujDugme;
    private javax.swing.JTextField duzinaKljucaInput;
    private javax.swing.JButton generisiKljucDugme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField lozinkaInput;
    private javax.swing.JButton sifrujDugme;
    // End of variables declaration//GEN-END:variables
}
